#! /bin/sh

set -e

report() {
    time_0=$(date -d "$1" +%s)
    for server_dir in $HOME/irc/*
    do
        echo $(basename $server_dir)
        for channel in $server_dir/\#*
        do
            log_file="${channel}/out"
            if test -f "$log_file"
            then
                printf "$(basename $channel) "
                awk -v time_0="$time_0" '$1 > time_0 && !($2 == "-!-")' $log_file \
                | wc -l
            fi
        done \
        | sort -n -k 2 \
        | column -t
        echo
    done
}

main() {
    time_0='00:00'  # Beginning of today (i.e midnight)

    while :
    do
        case "$1"
        in '')
            break
        ;; *)
            time_0="$1"
            shift 1
        esac
    done

    report "$time_0"
}

main "$@"
