#! /bin/sh

set -e

report() {
    time_0=$(date -d "$1" +%s)
    mention="$2"
    for server_dir in $HOME/irc/*
    do
        echo $(basename $server_dir)
        for channel in $server_dir/\#*
        do
            log_file="${channel}/out"
            if test -f "$log_file"
            then
                printf "$(basename $channel) "
                awk -v time_0="$time_0" '$1 > time_0 && !($2 == "-!-")' $log_file \
                | grep -i "$mention" \
                | wc -l
            fi
        done \
        | sort -n -k 2 \
        | column -t
        echo
    done
}

main() {
    time_0='00:00'  # Beginning of today (i.e midnight)
    mention=''

    while :
    do
        case "$1"
        in '')
            break
        ;; -t0)
            time_0="$2"
            shift 2
        ;; -m)
            mention="$2"
            shift 2
        ;; *)
            shift 1
        esac
    done

    report "$time_0" "$mention"
}

main "$@"
