#! /usr/bin/awk -f

BEGIN {
    bg[0] = 40
    bg[1] = 40
    bg[2] = 40

    fg[0] = 31
    fg[1] = 32
    fg[2] = 33
}

/^[0-9]/ && $2 == "-!-" {
    print_line(fg[0], bg[0], $0)
    next
}

/^[0-9]/ && $2 != "-!-" && $2 != nick {
    nick = $2
    nick_alt_count++
}

/^[0-9]/ && $2 != "-!-" {
    i = 1 + (nick_alt_count % 2)
    print_line(fg[i], bg[1], $0)
    next
}

function print_line(fg, bg, line) {
    print "\033[" fg "m\033[" bg "m" line "\033[0m"
}
