#! /usr/bin/awk -f

BEGIN {
    n = 2
    for (i=0; i<=n; i++) {
        c[i] = 32 + i
    }
}

/^[0-9]/ {
    nick_curr = $2
    if (nick_curr != nick_prev) {
        i = ++count % n
        nick_prev = nick_curr
    }
}

{
    print "\033[" c[i] "m\033[40m" $0 "\033[0m"
}
