#! /bin/bash

SERVER_PIPE='./in'
CHANNELS_FILE='./join'

awk '
    # Treating lines beginning with "//" as comments
    ! /^\/\// {
        channels = channels sep $1
        sep = ","
    }

    END {
        printf("/join %s\n", channels)
    }
    ' \
    "$CHANNELS_FILE" \
> "$SERVER_PIPE"
