#! /bin/sh

set -e

log_file='out'
lines=1000

while :
do
    case "$1"
    in '')
        break
    ;; -f)
        case "$2"
        in '')
            printf 'Error: option -f requires and argument.' >&2
            exit 1
        ;; *)
            log_file="$2"
            shift 2
        esac
    ;; -n)
        case "$2"
        in '')
            printf 'Error: option -n requires and argument.' >&2
            exit 1
        ;; *)
            lines="$2"
            shift 2
        esac
    esac
done

printf "log_file: \"$log_file\", lines: \"$lines\"\n" >&2

  stdbuf -o L tail -f "$log_file" -n "$lines" \
| stdbuf -o L ii-map-timestamp \
| stdbuf -o L ii-color-lines
